import pandas as pd
s = pd.read_csv(r"H:\lunwencp\shuailao\results\tables\clock_summary.csv")
print(f"Total tissues: {len(s)}")
print(f"Median r: {s['pearson_r'].median():.3f}")
print(f"r > 0.5: {(s['pearson_r']>0.5).sum()}/{len(s)}")
print(f"r > 0.3: {(s['pearson_r']>0.3).sum()}/{len(s)}")
print(f"Spearman > 0: {(s['spearman_r']>0).sum()}/{len(s)}")
print(f"Spearman = 0: {(s['spearman_r']==0).sum()}")
print()
print("Top 10:")
print(s.head(10)[["tissue","n_samples","n_features","mae","pearson_r","spearman_r","r2"]].to_string(index=False))
print()
print("Bottom 5:")
print(s.tail(5)[["tissue","n_samples","n_features","mae","pearson_r","spearman_r","r2"]].to_string(index=False))
